/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0054a2",
        "primary-container": "#106ccb",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a8c8ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#00468a",
        "on-primary-container": "#eaefff",
        "secondary": "#5156a9",
        "secondary-container": "#9fa3fd",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#bfc1ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#070765",
        "on-secondary-fixed-variant": "#393d90",
        "on-secondary-container": "#313588",
        "tertiary": "#004ac4",
        "tertiary-container": "#2362ea",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#eceeff",
        "surface": "#fafaf5",
        "surface-dim": "#dadad5",
        "surface-bright": "#fafaf5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4ef",
        "surface-container": "#eeeee9",
        "surface-container-high": "#e8e8e4",
        "surface-container-highest": "#e3e3de",
        "surface-variant": "#e3e3de",
        "on-surface": "#1a1c19",
        "on-surface-variant": "#414752",
        "background": "#fafaf5",
        "on-background": "#1a1c19",
        "outline": "#727784",
        "outline-variant": "#c1c6d4",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#a8c8ff",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f1f1ec",
        "surface-tint": "#005eb4",
      },
      fontFamily: {
        headline: ["Montserrat"],
        body: ["Hind"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};